services:
  postgres:
    image: postgres:15
    container_name: granja-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: granja_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - granja-network

volumes:
  pgdata:

networks:
  granja-network:
    driver: bridge
