services:
  mongodb:
    image: mongo:7.0
    container_name: granja-mongodb
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: banco
    volumes:
      - mongo_data:/data/db
    networks:
      - granja-network

  postgres:
    image: postgres:15
    container_name: granja-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: granja_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - granja-network

volumes:
  mongo_data:
  pgdata:

networks:
  granja-network:
    driver: bridge
